# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: 0.12

version: "{build}"
build: off
deploy: off

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - ps: "npm test # PowerShell"
  - cmd: "npm test"

cache:
  - '%APPDATA%\npm-cache'
  - node_modules
